;;;; -*- mode: common-lisp; coding: utf-8; -*-

(in-package :ml-survey/questionnaire)

(spinneret:with-html (:p "Bitte beurteilen Sie auf einer Skala von 1 (stimme gar nicht zu) bis 7 (stimme
voll zu), inwieweit Sie den folgenden Aussagen in Bezug auf die Ihnen
vorliegende Website zustimmen. Vielen Dank!"))

(multi-form
  (:ask "Das Layout wirkt zu gedrängt."
   :group "likert-simplicity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Das Layout ist gut zu erfassen."
   :group "likert-simplicity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Das Layout erscheint angenehm gegliedert."
   :group "likert-simplicity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Die Seite erscheint zu uneinheitlich."
   :group "likert-simplicity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))

  (:ask "Auf der Seite passt alles zusammen."
   :group "likert-simplicity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Die Seitengestaltung ist uninteressant."
   :group "likert-diversity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Das Layout ist originell."
   :group "likert-diversity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Die Gestaltung wirkt einfallslos."
   :group "likert-diversity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Das Layout wirkt dynamisch."
   :group "likert-diversity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Das Layout ist angenehm vielseitig."
   :group "likert-diversity"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Die farbliche Gesamtgestaltung wirkt attraktiv."
   :group "likert-colorfulness"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Die Farben passen nicht zueinander."
   :group "likert-colorfulness"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Der Farbeinsatz ist nicht gelungen."
   :group "likert-colorfulness"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Die Farben haben eine angenehme Wirkung."
   :group "likert-colorfulness"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Das Layout ist professionell."
   :group "likert-craftsmanship"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Das Layout ist nicht zeitgemäß."
   :group "likert-craftsmanship"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Die Seite erscheint mit Sorgfalt gemacht."
   :group "likert-craftsmanship"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu"))
  (:ask "Das Layout wirkt konzeptlos."
   :group "likert-craftsmanship"
   :style "list-style:none"
   :choices (:single "1 Stimme gar nicht zu"
                     "2 Stimme nicht zu"
                     "3 Stimme eher nicht zu"
                     "4 neutral"
                     "5 Stimme eher zu"
                     "6 Stimme zu"
                     "7 Stimme voll zu")))
